//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alb.Omdehsara.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCategoryProperty
    {
        public TblCategoryProperty()
        {
        }
    
        public int ID { get; set; }
        public long CategoryID { get; set; }
        public string PropertyName { get; set; }
        public string PropertyName_En { get; set; }
        public string Unit { get; set; }
        public string Unit_En { get; set; }
        public Nullable<int> SortNumber { get; set; }
        public bool ShowName { get; set; }
        public bool ShowForSearch { get; set; }
        public string PropertyType { get; set; }
        public string ListSubject { get; set; }
    }
}
