//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alb.Omdehsara.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblConstant
    {
        public TblConstant()
        {
        }
        public int ID { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public string ParentSubject { get; set; }
        public int? SortOrder { get; set; }

    }
}
