//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alb.Omdehsara.Common.Product
{
    using System;
    using System.Collections.Generic;

    public partial class ColorCategories : TblColor
    {
        public ColorCategories()
        {
        }
        public IEnumerable<TblCategory> Categoryies { get; set; }
    }
}
