//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alb.Omdehsara.Common.Product
{
    using System;
    using System.Collections.Generic;

    public partial class ProductTypeView : TblProductType
    {
        public ProductTypeView()
        {

        }
        public string MainImageUrl { get; set; }
        public string ProductUrl { get; set; }
        public string BrandName { get; set; }
        public string BrandImageUrl { get; set; }
        public string CountryName { get; set; }
        public int Quantity { get; set; }
        public int UnitID { get; set; }
        public int UnitQuantity { get; set; }
        public string UnitName { get; set; }
        public int PriceHour
        {
            get;
            set;
        }
        public int PriceMinute
        {
            get;
            set;
        }
    }
}
