//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alb.Omdehsara.Common.Product
{
    using System;
    using System.Collections.Generic;

    public partial class ProductLocationSearchOption
    {
        public ProductLocationSearchOption()
        {
        }
        public long? ProductTypeID { get; set; }
        public long? ProductID { get; set; }
        public long? CategoryID { get; set; }
        public string ProductTitle { get; set; }
        public Nullable<int> BrandID { get; set; }
        public int? ColorID { get; set; }
        public int? SizeID { get; set; }
        public int? StoreID { get; set; }
        public int? ShelfID { get; set; }
        public int? Row { get; set; }
        public int? Column { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public int? UserID { get; set; }
        public int? PageSize { get; set; }
        public int? PageIndex { get; set; }
    }
}
