//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alb.Omdehsara.Common.Product
{
    using System;
    using System.Collections.Generic;

    public partial class StoreProduct
    {
        public StoreProduct()
        {
        }
        public Nullable<long> ProductTypeID { get; set; }
        public string Code { get; set; }
        public byte Enabled { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int ShelfID { get; set; }
        public int Row { get; set; }
        public int Column { get; set; }
        public long ProductID { get; set; }
        public DateTime InsDate { get; set; }
        public int UserID { get; set; }
        public int InOut { get; set; }
        public long? OrderID { get; set; }
    }
}
