//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alb.Omdehsara.Common.Product
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductType
    {
        public TblProductType()
        {
            MinOrderQuantity = 1;
        }


        public long ID { get; set; }
        public long CategoryID { get; set; }
        public string Description { get; set; }
        public Nullable<int> PreviousPrice { get; set; }
        public Nullable<int> Price { get; set; }
        public int UserID { get; set; }
        public long VisitCount { get; set; }
        public Nullable<int> Freight { get; set; }
        public byte Enabled { get; set; }
        public string ProductTitle { get; set; }
        public Nullable<int> MainImageID { get; set; }
        public Nullable<bool> HasGallery { get; set; }
        public string ProductKeywords { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> Count { get; set; }
        public System.DateTime InsDate { get; set; }
        public Nullable<DateTime> PriceDate { get; set; }
        public bool ShowInFirstPage { get; set; }
        public string Country { get; set; }
        public int? MinOrderQuantity { get; set; }
        public int UnitID { get; set; }
    }
}
